### ISSUE TITLE
Migration to new pinecone API

### ISSUE THREAD

**Issue by JanRuettinger** [henomis/pinecone-go#3]
Pinecone just announced a new API.

More info here: https://docs.pinecone.io/docs/new-api
Pretty much all API endpoints have changed which means the library needs a substantial PR. 

Anybody interested in doing it together or jumping on it?

**Comment by henomis** [comment]
This will be implemented here: https://github.com/henomis/pinecone-go/pull/4

**Comment by henomis** [comment]
released v2.0.0

**Comment by JanRuettinger** [comment]
That was quick! Great work!
